server:
  port: 8082
spring:
  profiles:
    active: dev
#多文档块
---
server:
  port: 8083
spring:
  profiles: dev



---
server:
  port: 8084
spring:
  profiles: prod

#person:
#  lastName: xiaoli
#  age: 18
#  birth: 2000/01/04
#  maps: {k1: v1,k2: v2}
#  lists:
#    - lisi
#    - zhaowu
#  dog:
#    name: dog
#    age: 2

